version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: ${POSTGRES_PORT_OUTSIDE:-5432}
        protocol: tcp
###< doctrine/doctrine-bundle ###
